package com.akari.retailer.navigation

object Routes {
    const val SALE_ENTRY = "sale_entry"
    const val SETTINGS = "settings"
    const val HISTORY = "history"
    const val REPORTS = "reports"
    const val TRENDS = "trends"
    const val EXPENSES = "expenses"
    const val EXPENSE_ADD = "expense_add"
    const val EXPENSE_DETAIL = "expense_detail/{expenseId}"
    const val EXPENSE_EDIT = "expense_edit/{expenseId}"
    const val INVENTORY = "inventory"
    const val INVENTORY_ADD = "inventory_add"
    const val INVENTORY_DETAIL = "inventory_detail/{productId}"
    const val INVENTORY_EDIT = "inventory_edit/{productId}"
    const val STOCK_HISTORY = "stock_history/{productId}/{productName}"
    const val STOCK_ADJUSTMENT = "stock_adjustment"
    const val PURCHASE_ORDERS = "purchase_orders"
    const val PURCHASE_ORDER_ADD = "purchase_order_add"
    const val PURCHASE_ORDER_DETAIL = "purchase_order_detail/{orderId}"
    const val PURCHASE_ORDER_EDIT = "purchase_order_edit/{orderId}"
    const val RECEIVE_ORDER = "receive_order/{orderId}"
    const val CUSTOMERS = "customers"
    const val CUSTOMER_ADD = "customer_add"
    const val CUSTOMER_EDIT = "customer_edit/{customerId}"
    const val CUSTOMER_DETAIL = "customer_detail/{customerId}"
    const val SUPPLIERS = "suppliers"
    const val SUPPLIER_ADD = "supplier_add"
    const val SUPPLIER_DETAIL = "supplier_detail/{supplierId}"
    const val SUPPLIER_EDIT = "supplier_edit/{supplierId}"
}
